import { useSelector } from "react-redux";
import {
    Card,
    CardContent,
    CardFooter,
    CardHeader,
    CardTitle,
  } from "../ui/card";
  import { Skeleton } from "@/components/ui/skeleton";
import { RootState } from "@/types";
  
export const Explanation = () => {
    const { explanation, active } = useSelector((state: RootState) => state.quiz);
    return (
        <section className="mx-auto max-w-4xl w-full py-10" id="explanation">
        <Card className="p-5">
          <CardHeader>
            <CardTitle>{active?.question}</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="font-medium text-lg mb-2">Answer: </p>
            <p className="font-medium text-lg mb-2">Explanation: </p>
            {explanation.visible ? (
              <pre className="text-wrap">{explanation.content}</pre>
              // <p dangerouslySetInnerHTML={{__html: explanation.content}}></p>
            ) : (
              <>
                <Skeleton className="w-3/4 h-[16px] rounded-md mb-2" />
                <Skeleton className="w-full h-[48px] rounded-md" />
              </>
            )}
          </CardContent>
          <CardFooter>
            <p className="text-wrap text-xs">
              <strong>Disclaimer: </strong>
              This explanation is generated by generative artificial
              intelligence. It means that the answer may not be 100% accurate.
              Always verify the answer with more reliable sources.
            </p>
          </CardFooter>
        </Card>
      </section>
    )
}