import { useSelector } from "react-redux";
import {
  Card,
  CardContent,
  CardFooter,
  CardHeader,
  CardTitle,
} from "../ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { RootState } from "@/types";
import Markdown from "react-markdown";
import { ExplanationButton } from "./ExplanationButton";

export const Explanation = () => {
  const { explanation, active, state } = useSelector(
    (state: RootState) => state.quiz
  );
  return (
    <Card className="p-4 max-w-4xl">
      <CardHeader>
        <CardTitle>{active?.question}</CardTitle>
      </CardHeader>
      <CardContent>
        {!explanation.visible && (
          <>
            <ExplanationButton variant="link" state={state} active={active} />
          </>
        )}
        {explanation.visible && explanation.content.length > 0 && (
          <>
            {/* <p className="font-medium text-lg mb-2">Explanation: </p> */}
            <Markdown children={explanation.content} />
          </>
        )}
        {explanation.visible && explanation.content.length === 0 && (
          <>
            <p className="font-medium text-lg mb-2">Answer: </p>
            <Skeleton className="w-3/4 h-[16px] rounded-md mb-2" />
            <p className="font-medium text-lg mb-2">Explanation: </p>
            <Skeleton className="w-3/4 h-[16px] rounded-md mb-2" />
            <Skeleton className="w-full h-[48px] rounded-md" />
          </>
        )}
      </CardContent>
      <CardFooter>
        <p className="text-wrap text-xs">
          <strong>Disclaimer: </strong>
          This explanation is generated by generative artificial intelligence.
          It means that the answer may not be 100% accurate. Always verify the
          answer with more reliable sources.
        </p>
      </CardFooter>
    </Card>
  );
};
